;;; disproject-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from disproject.el

(put 'disproject-custom-suffixes 'safe-local-variable #'always)
 (autoload 'disproject-dispatch "disproject" nil t)
(register-definition-prefixes "disproject" '("disproject-"))

;;; End of scraped data

(provide 'disproject-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; disproject-autoloads.el ends here
