;;; projection-multi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from projection-multi.el

(autoload 'projection-multi-projection-targets "projection-multi" "\
`compile-multi' target generator function for `projection-commands' in PROJECT.
When set the generated targets will be prefixed with PROJECT-TYPE-PREFIX. If
not set PROJECT will be determined automatically.

The generated candidates will be of the form
prefix:project-type:project-command.

(fn &optional PROJECT-TYPE-PREFIX PROJECT)")
(autoload 'projection-multi-projection "projection-multi" "\
`compile-multi' wrapper for only projection targets." t)
(autoload 'projection-multi-compile "projection-multi" "\
Variant of `compile-multi' which includes project specific targets." t)
(register-definition-prefixes "projection-multi" '("projection-multi-"))


;;; Generated autoloads from projection-multi-cmake.el

(autoload 'projection-multi-cmake-targets "projection-multi-cmake" "\
`compile-multi' target generator function for CMake projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-cmake "projection-multi-cmake" "\
`compile-multi' wrapper for only CMake targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-cmake #'projection-multi-cmake-targets))
(register-definition-prefixes "projection-multi-cmake" '("projection-multi-cmake-"))


;;; Generated autoloads from projection-multi-ctest.el

(autoload 'projection-multi-ctest-targets "projection-multi-ctest" "\
`compile-multi' target generator function for CMake ctest targets.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-ctest "projection-multi-ctest" "\
`compile-multi' wrapper for only CMake ctest targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-cmake #'projection-multi-ctest-targets))
(register-definition-prefixes "projection-multi-ctest" '("projection-multi-ctest-"))


;;; Generated autoloads from projection-multi-golang.el

(autoload 'projection-multi-golang-targets "projection-multi-golang" "\
`compile-multi' target generator function for Golang projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-golang "projection-multi-golang" "\
`compile-multi' wrapper for only golang targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-golang #'projection-multi-golang-targets))


;;; Generated autoloads from projection-multi-gradle.el

(autoload 'projection-multi-gradle-targets "projection-multi-gradle" "\
`compile-multi' target generator function for Gradle projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-gradle "projection-multi-gradle" "\
`compile-multi' wrapper for only Gradle targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-gradle #'projection-multi-gradle-targets))
(register-definition-prefixes "projection-multi-gradle" '("projection-multi-gradle-"))


;;; Generated autoloads from projection-multi-make.el

(autoload 'projection-multi-make-targets "projection-multi-make" "\
`compile-multi' target generator function for Makefile projects.
When set the generated targets will be prefixed with PROJECT-TYPE.
When set this function will read targets from FILE-NAME instead of
the first Makefile it finds in the current directory.

(fn &optional PROJECT-TYPE FILE-NAME)")
(autoload 'projection-multi-compile-make "projection-multi-make" "\
`compile-multi' wrapper for only Make targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-make #'projection-multi-make-targets))
(register-definition-prefixes "projection-multi-make" '("projection-multi-make-"))


;;; Generated autoloads from projection-multi-meson.el

(autoload 'projection-multi-meson-targets "projection-multi-meson" "\
`compile-multi' target generator function for Meson projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-meson "projection-multi-meson" "\
`compile-multi' wrapper for only Meson targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-meson #'projection-multi-meson-targets))
(register-definition-prefixes "projection-multi-meson" '("projection-multi-meson--t"))


;;; Generated autoloads from projection-multi-npm-scripts.el

(autoload 'projection-multi-npm-script-targets "projection-multi-npm-scripts" "\
`compile-multi' target generator function for npm projects with scripts.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-npm-scripts "projection-multi-npm-scripts" "\
`compile-multi' wrapper for only npm script targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-npm #'projection-multi-npm-script-targets))
(register-definition-prefixes "projection-multi-npm-scripts" '("projection-multi-npm-scripts-"))


;;; Generated autoloads from projection-multi-poetry-poe.el

(autoload 'projection-multi-poetry-poe-targets "projection-multi-poetry-poe" "\
`compile-multi' target generator function for poetry-poe projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-poetry-poe "projection-multi-poetry-poe" "\
`compile-multi' wrapper for only poetry-poe targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-python-poetry #'projection-multi-poetry-poe-targets))
(register-definition-prefixes "projection-multi-poetry-poe" '("projection-multi-poetry-poe-"))


;;; Generated autoloads from projection-multi-pytest.el

(autoload 'projection-multi-pytest-targets "projection-multi-pytest" "\
`compile-multi' target generator function for Pytest projects.")
(autoload 'projection-multi-pytest "projection-multi-pytest" "\
`compile-multi' wrapper for only Pytest targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets (list projection-project-type-django projection-project-type-python-pip projection-project-type-python-pkg projection-project-type-python-toml projection-project-type-python-tox projection-project-type-python-pipenv projection-project-type-python-poetry) #'projection-multi-pytest-targets))
(register-definition-prefixes "projection-multi-pytest" '("projection-multi-pyt"))


;;; Generated autoloads from projection-multi-rustic.el

(autoload 'projection-multi-rustic-targets "projection-multi-rustic" "\
`compile-multi' target generator function for `rustic' projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-rustic "projection-multi-rustic" "\
`compile-multi' wrapper for only `rustic' targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-rust-cargo #'projection-multi-rustic-targets))


;;; Generated autoloads from projection-multi-tox.el

(autoload 'projection-multi-tox-targets "projection-multi-tox" "\
`compile-multi' target generator function for Tox projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-tox "projection-multi-tox" "\
`compile-multi' wrapper for only tox targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-python-tox #'projection-multi-tox-targets))
(register-definition-prefixes "projection-multi-tox" '("projection-multi-tox-"))


;;; Generated autoloads from projection-multi-vscode-tasks.el

(autoload 'projection-multi-compile-vscode-targets "projection-multi-vscode-tasks" "\
`compile-multi' target generator function for VSCode task projects.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-vscode-tasks "projection-multi-vscode-tasks" "\
`compile-multi' wrapper for only VSCode task targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-vscode-tasks #'projection-multi-compile-vscode-targets))
(register-definition-prefixes "projection-multi-vscode-tasks" '("projection-multi-vscode-tasks-"))


;;; Generated autoloads from projection-multi-yarn-scripts.el

(autoload 'projection-multi-yarn-script-targets "projection-multi-yarn-scripts" "\
`compile-multi' target generator function for Yarn projects with scripts.
When set the generated targets will be prefixed with PROJECT-TYPE.

(fn &optional PROJECT-TYPE)")
(autoload 'projection-multi-compile-yarn-scripts "projection-multi-yarn-scripts" "\
`compile-multi' wrapper for only yarn script targets." t)
(with-eval-after-load 'projection-types (projection-type-append-compile-multi-targets projection-project-type-yarn #'projection-multi-yarn-script-targets))
(register-definition-prefixes "projection-multi-yarn-scripts" '("projection-multi-yarn-scripts-"))

;;; End of scraped data

(provide 'projection-multi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; projection-multi-autoloads.el ends here
