;;; esxml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from css-lite.el

(register-definition-prefixes "css-lite" '("*css-stream*" "*indent-css*" "+newline+" "css" "expand-tree" "inline-css" "make-css-" "process-css-" "selector-to-string" "string-cut" "to-string"))


;;; Generated autoloads from esxml.el

(register-definition-prefixes "esxml" '("attr" "esxml-" "pp-esxml-to-xml" "string-trim-whitespace" "sxml-to-" "xml-to-esxml"))


;;; Generated autoloads from esxml-form.el

(register-definition-prefixes "esxml-form" '("esxml-"))


;;; Generated autoloads from esxml-form-tests.el

(register-definition-prefixes "esxml-form-tests" '("esxml-form-field-set--test-defaults" "my-test-db"))


;;; Generated autoloads from esxml-html.el

(register-definition-prefixes "esxml-html" '("esxml-"))


;;; Generated autoloads from esxml-query.el

(register-definition-prefixes "esxml-query" '("esxml-"))


;;; Generated autoloads from esxml-query-tests.el

(register-definition-prefixes "esxml-query-tests" '("esxml-query-document"))


;;; Generated autoloads from esxpath.el

(register-definition-prefixes "esxpath" '("esxpath" "on-nodeset" "plambda" "test-sheet"))

;;; End of scraped data

(provide 'esxml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; esxml-autoloads.el ends here
