;;; projection-multi-embark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from projection-multi-embark.el

 (progn (autoload 'projection-multi-embark-set-build-command "projection-commands" nil t) (autoload 'projection-multi-embark-set-build-command-dwim "projection-commands" nil t))
 (progn (autoload 'projection-multi-embark-set-configure-command "projection-commands" nil t) (autoload 'projection-multi-embark-set-configure-command-dwim "projection-commands" nil t))
 (progn (autoload 'projection-multi-embark-set-test-command "projection-commands" nil t) (autoload 'projection-multi-embark-set-test-command-dwim "projection-commands" nil t))
 (progn (autoload 'projection-multi-embark-set-run-command "projection-commands" nil t) (autoload 'projection-multi-embark-set-run-command-dwim "projection-commands" nil t))
 (progn (autoload 'projection-multi-embark-set-package-command "projection-commands" nil t) (autoload 'projection-multi-embark-set-package-command-dwim "projection-commands" nil t))
 (progn (autoload 'projection-multi-embark-set-install-command "projection-commands" nil t) (autoload 'projection-multi-embark-set-install-command-dwim "projection-commands" nil t))
(autoload 'projection-multi-embark-setup-command-map "projection-multi-embark" "\
Setup `projection-multi-embark' command map in relevent embark maps.")
(register-definition-prefixes "projection-multi-embark" '("projection-multi-embark-"))

;;; End of scraped data

(provide 'projection-multi-embark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; projection-multi-embark-autoloads.el ends here
