;;; projection-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from projection.el

(defvar projection-per-project-type-map (let ((map (make-sparse-keymap))) (define-key map "c" '("CMake")) (define-key map "cp" 'projection-cmake-set-preset) (define-key map "cb" 'projection-cmake-set-build-type) (define-key map "cd" 'projection-cmake-clear-build-directory) (define-key map "cl" 'projection-cmake-set-configure-log-level) (define-key map "cv" 'projection-cmake-set-build-verbosely) (define-key map "g" '("Golang")) (define-key map "gp" 'projection-golang-set-package) (define-key map "m" '("Meson")) (define-key map "mb" 'projection-meson-set-build-type) (define-key map "mc" 'projection-meson-set-build-option) map) "\
Keymap containing commands specific to each project type.")
(defvar projection-map (let ((map (make-sparse-keymap))) (define-key map (kbd "SPC") '("Extensions" projection-per-project-type-map)) (define-key map "1" 'projection-set-primary-project-type) (define-key map "2" 'projection-update-extra-project-types) (define-key map "I" 'projection-show-project-info) (define-key map (kbd "DEL") 'projection-cache-clear) (define-key map "l" 'projection-artifacts-list) (define-key map (kbd "TAB") 'projection-find-other-file) (define-key map "o" 'projection-find-other-file) (define-key map "h" 'projection-hook) (define-key map "H" 'projection-hook-clear) (define-key map "m" 'ibuffer-projection-current-project) (define-key map "M" 'ibuffer-projection-toggle-filter-groups) (define-key map "c" 'projection-commands-build-project) (define-key map "g" 'projection-commands-configure-project) (define-key map "t" 'projection-commands-test-project) (define-key map "r" 'projection-commands-run-project) (define-key map "p" 'projection-commands-run-project) (define-key map "k" 'projection-commands-package-project) (define-key map "i" 'projection-commands-install-project) map) "\
Keymap for projection project-management bindings.")
(register-definition-prefixes "projection" '("projection-"))


;;; Generated autoloads from projection-artifacts.el

(autoload 'projection-artifacts-list "projection-artifacts" "\
Interactive function to select artifacts.
Calls `projection-artifacts-default-list-action' on ARTIFACT.

(fn ARTIFACT)" t)
(register-definition-prefixes "projection-artifacts" '("projection-artifacts-"))


;;; Generated autoloads from projection-commands.el

 (autoload 'projection-commands-configure-project     "projection-commands" nil t)
 (autoload 'projection-commands-set-configure-command "projection-commands" nil t)
 (autoload 'projection-commands-build-project     "projection-commands" nil t)
 (autoload 'projection-commands-set-build-command "projection-commands" nil t)
 (autoload 'projection-commands-test-project     "projection-commands" nil t)
 (autoload 'projection-commands-set-test-command "projection-commands" nil t)
 (autoload 'projection-commands-run-project     "projection-commands" nil t)
 (autoload 'projection-commands-set-run-command "projection-commands" nil t)
 (autoload 'projection-commands-package-project     "projection-commands" nil t)
 (autoload 'projection-commands-set-package-command "projection-commands" nil t)
 (autoload 'projection-commands-install-project     "projection-commands" nil t)
 (autoload 'projection-commands-set-install-command "projection-commands" nil t)
(autoload 'projection-commands-set-command-for-type "projection-commands" "\
Save COMMAND as the compilation command CMD-TYPE for PROJECT.

(fn COMMAND PROJECT CMD-TYPE)" t)
(register-definition-prefixes "projection-commands" '("projection-command"))


;;; Generated autoloads from projection-core-cache.el

(autoload 'projection-cache-clear "projection-core-cache" "\
Interactively clear cached variables for the current project.
Calls `projection-cache-clear-all' or `projection-cache-clear-single' based on
the value of CLEAR-ALL.

(fn CLEAR-ALL)" t)
(register-definition-prefixes "projection-core-cache" '("projection-"))


;;; Generated autoloads from projection-core-commands.el

(autoload 'projection-set-primary-project-type "projection-core-commands" "\
Set the primary project type for PROJECT to PROJECT-TYPE.
With prefix argument prompt for all possible project types not just those
matching the current project.

(fn PROJECT PROJECT-TYPE)" t)
(autoload 'projection-update-extra-project-types "projection-core-commands" "\
Update the list of project types matching the PROJECT.
ADD-TYPES is a list of project types to start associating with PROJECT.
REMOVE-TYPES is a list of project types to stop associating with PROJECT.

(fn PROJECT ADD-TYPES REMOVE-TYPES)" t)
(autoload 'projection-show-project-info "projection-core-commands" "\
Display info for the PROJECT with respect to PROJECT-TYPES.

(fn PROJECT PROJECT-TYPES)" t)


;;; Generated autoloads from projection-core-log.el

(register-definition-prefixes "projection-core-log" '("projection-"))


;;; Generated autoloads from projection-core-match.el

(register-definition-prefixes "projection-core-match" '("projection-"))


;;; Generated autoloads from projection-core-misc.el

(register-definition-prefixes "projection-core-misc" '("projection--"))


;;; Generated autoloads from projection-core-type.el

(register-definition-prefixes "projection-core-type" '("projection-"))


;;; Generated autoloads from projection-customize-compilation.el

(autoload 'projection-customize-compilation-buffer-name-function "projection-customize-compilation" "\
Sample project specific `compilation-buffer-name-function'.
To use set either `compilation-buffer-name-function' or
`project-compilation-buffer-name-function' to this function.

See `compilation-buffer-name-function' for a description of NAME-OF-MODE.

(fn NAME-OF-MODE)")
(autoload 'projection-customize-compilation-mode "projection-customize-compilation" "\
Minor mode to customize `compilation-mode' with `projection' features.

This is a minor mode.  If called interactively, toggle the
`Projection-Customize-Compilation mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `projection-customize-compilation-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "projection-customize-compilation" '("projection-customize-compilation-"))


;;; Generated autoloads from projection-find.el

(autoload 'projection-find-other-file "projection-find" "\
Switch between similar files to the current file in this project.
This function will huerestically determine all files in the project similar
to the current file and then `find-file' it. For example this can be used to
switch between C++ header and implementation files assuming the two have the
same basename and a different extension. Similarly this function also includes
any files with test suffixes or prefixes associated with the current project
type. See `projection-type' and `projection-find-other-file-suffix' for
some of the options that impact file resolution.

The order of files cycled from this function is deterministic, and invoking it
repeatedly should cycle between related project files. When invoked with
SELECT-INTERACTIVELY and there's more than one possible file this function could
switch to then you will be dropped into a `completing-read' session with all
possible files and the first match being the one you would've switched to if
SELECT-INTERACTIVELY is not set.

(fn &optional SELECT-INTERACTIVELY)" t)
(register-definition-prefixes "projection-find" '("projection-find-"))


;;; Generated autoloads from projection-hook.el

(autoload 'projection-hook "projection-hook" "\
Update the hooked functions for the current project.
HOOK-ENTRIES should be a list of entries from `projection-hook-functions'.
Unless NO-UPDATE is given the changes to the hook functions will be
retroactively applied to every buffer in the current project with
`projection-hook-mode' enabled.

(fn HOOK-ENTRIES &optional NO-UPDATE)" t)
(autoload 'projection-hook-clear "projection-hook" "\
Clear all project hooks enabled for the current project.
See `projection-hook' for a description of NO-UPDATE.

(fn &optional NO-UPDATE)" t)
(autoload 'projection-hook-mode "projection-hook" "\
Minor mode to enable any functions hooked into the current project.

This is a minor mode.  If called interactively, toggle the
`Projection-Hook mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `projection-hook-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-projection-hook-mode 'globalized-minor-mode t)
(defvar global-projection-hook-mode nil "\
Non-nil if Global Projection-Hook mode is enabled.
See the `global-projection-hook-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-projection-hook-mode'.")
(custom-autoload 'global-projection-hook-mode "projection-hook" nil)
(autoload 'global-projection-hook-mode "projection-hook" "\
Toggle Projection-Hook mode in all buffers.
With prefix ARG, enable Global Projection-Hook mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Projection-Hook mode is enabled in all buffers where
`projection-hook--global-turn-on' would do it.

See `projection-hook-mode' for more information on Projection-Hook mode.

(fn &optional ARG)" t)
(register-definition-prefixes "projection-hook" '("projection-hook-"))


;;; Generated autoloads from projection-ibuffer.el

 (autoload 'ibuffer-make-column-projection-name "projection-ibuffer")
 (autoload 'ibuffer-filter-by-projection-files "projection-ibuffer" nil t)
 (autoload 'ibuffer-do-sort-by-projection-name "projection-ibuffer" nil t)
 (autoload 'ibuffer-make-column-projection-relative-file "projection-ibuffer")
(autoload 'ibuffer-projection-current-project "projection-ibuffer" "\
Open an IBuffer window showing all buffers in the current project.

Let user choose another project when PROMPT-FOR-PROJECT is supplied.

(fn PROMPT-FOR-PROJECT)" t)
(autoload 'ibuffer-projection-set-filter-groups "projection-ibuffer" "\
Set ibuffer filter groups for all projects that have open buffers." t)
(autoload 'ibuffer-projection-unset-filter-groups "projection-ibuffer" "\
Remove ibuffer filter groups set by `ibuffer-projection-set-filter-groups'.
Returns t if any such groups were removed otherwise returns nil." t)
(autoload 'ibuffer-projection-toggle-filter-groups "projection-ibuffer" "\
Toggle the inclusion of project-filter-groups in ibuffer.
This calls `ibuffer-projection-set-filter-groups' or
`ibuffer-projection-unset-filter-groups' depending on the
current value of `ibuffer-filter-groups'." t)
(register-definition-prefixes "projection-ibuffer" '("projection-ibuffer-"))


;;; Generated autoloads from projection-recentf.el

(autoload 'projection-recentf "projection-recentf" "\
Variant of `recentf-open' for project files.
Will call `recentf-open' with FILE.

(fn FILE)" t)
(register-definition-prefixes "projection-recentf" '("projection-recentf--"))


;;; Generated autoloads from projection-type-cmake.el

(autoload 'projection-cmake-set-preset "projection-type-cmake" "\
Set CMake preset for BUILD-TYPE to PRESET for PROJECT.

(fn PROJECT BUILD-TYPE PRESET)" t)
(autoload 'projection-cmake-set-kit "projection-type-cmake" "\
Set CMake kit to KIT for PROJECT.

(fn PROJECT KIT)" t)
(autoload 'projection-cmake--file-api-create-query-file "projection-type-cmake" "\
Create a file-api client query file for projection.")
(autoload 'projection-cmake--file-api-create-query-hook "projection-type-cmake" "\
Helper to create a CMake query file before configuring the CMake PROJECT.

(fn &key PROJECT &allow-other-keys)")
(autoload 'projection-cmake--file-api-clear-cache-on-configure "projection-type-cmake" "\
Clear CMake cache on reconfiguring PROJECT.

(fn &key PROJECT &allow-other-keys)")
(add-hook 'projection-commands-pre-configure-hook #'projection-cmake--file-api-create-query-hook)
(add-hook 'projection-commands-post-configure-hook #'projection-cmake--file-api-clear-cache-on-configure)
 (autoload 'projection-cmake-set-build-type "projection-type-cmake" nil 'interactive)
 (autoload 'projection-cmake-set-configure-log-level "projection-type-cmake" nil 'interactive)
 (autoload 'projection-cmake-set-build-verbosely "projection-type-cmake" nil 'interactive)
 (autoload 'projection-cmake-set-install-verbosely "projection-type-cmake" nil 'interactive)
 (autoload 'projection-cmake-clear-build-directory "projection-type-cmake" nil 'interactive)
(register-definition-prefixes "projection-type-cmake" '("projection-c"))


;;; Generated autoloads from projection-type-golang.el

(autoload 'projection-golang-set-package "projection-type-golang" "\
Set the target package for PROJECT to PACKAGE.

(fn PROJECT PACKAGE)" t)
(register-definition-prefixes "projection-type-golang" '("projection-golang-"))


;;; Generated autoloads from projection-type-gradle.el

(register-definition-prefixes "projection-type-gradle" '("projection-gradle-"))


;;; Generated autoloads from projection-type-meson.el

 (autoload 'projection-meson-set-build-type "projection-type-meson" nil 'interactive)
(autoload 'projection-meson-set-build-option "projection-type-meson" "\
Interactively set a Meson build-option OPTION for PROJECT to VALUE.

(fn PROJECT OPTION VALUE)" t)
(register-definition-prefixes "projection-type-meson" '("projection-"))


;;; Generated autoloads from projection-types.el

 (autoload 'projection-tox-clear-work-directory "projection-types" nil 'interactive)
(register-definition-prefixes "projection-types" '("projection-"))


;;; Generated autoloads from projection-utils.el

(register-definition-prefixes "projection-utils" '("projection--"))

;;; End of scraped data

(provide 'projection-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; projection-autoloads.el ends here
