;;; consult-eglot-embark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-eglot-embark.el

(autoload 'consult-eglot-embark-export-grep "consult-eglot-embark" "\
Exporter for a `consult-eglot' session to a grep buffer.
CANDIDATES is the collection of completion candidates to include int he grep
buffer.

(fn CANDIDATES)")
(autoload 'consult-eglot-embark-goto-symbol "consult-eglot-embark" "\
Jump to a `consult-eglot' CANDIDATE through `embark-act'.

(fn CANDIDATE)")
(defvar consult-eglot-embark-mode nil "\
Non-nil if Consult-Eglot-Embark mode is enabled.
See the `consult-eglot-embark-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `consult-eglot-embark-mode'.")
(custom-autoload 'consult-eglot-embark-mode "consult-eglot-embark" nil)
(autoload 'consult-eglot-embark-mode "consult-eglot-embark" "\
Setup `consult-eglot' actions for embark.

This is a global minor mode.  If called interactively, toggle the
`Consult-Eglot-Embark mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='consult-eglot-embark-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)

;;; End of scraped data

(provide 'consult-eglot-embark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-eglot-embark-autoloads.el ends here
