;;; symbol-overlay-mc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from symbol-overlay-mc.el

(autoload 'symbol-overlay-mc-mark-all "symbol-overlay-mc" "\
Mark all symbol overlays using multiple cursors." t)
(autoload 'symbol-overlay-mc-insert-into-casual-tmenu "symbol-overlay-mc" nil t)

;;; End of scraped data

(provide 'symbol-overlay-mc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; symbol-overlay-mc-autoloads.el ends here
