;;; mini-echo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from mini-echo.el

(autoload 'mini-echo-toggle "mini-echo" "\
Enable or disable selected segment temporarily.
If optional arg RESET is non-nil, clear all toggled segments.

(fn &optional RESET)" t)
(defvar mini-echo-mode nil "\
Non-nil if Mini-Echo mode is enabled.
See the `mini-echo-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `mini-echo-mode'.")
(custom-autoload 'mini-echo-mode "mini-echo" nil)
(autoload 'mini-echo-mode "mini-echo" "\
Minor mode to show buffer status in echo area.

This is a global minor mode.  If called interactively, toggle the
`Mini-Echo mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='mini-echo-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "mini-echo" '("mini-echo-"))


;;; Generated autoloads from mini-echo-segments.el

(autoload 'mini-echo-define-segment "mini-echo-segments" "\
Define a mini echo segment NAME with DOCSTRING and PROPS.

(fn NAME DOCSTRING &rest PROPS)" nil t)
(function-put 'mini-echo-define-segment 'lisp-indent-function 'defun)
(function-put 'mini-echo-define-segment 'doc-string-elt 2)
(register-definition-prefixes "mini-echo-segments" '("mini-echo-"))

;;; End of scraped data

(provide 'mini-echo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; mini-echo-autoloads.el ends here
